global:
  # options: [hoodi, mainnet]
  network: hoodi
  ports:
    p2pPort: 30303
    httpPort: 8545
    wsPort: 8546
    authPort: 8551
    metricsPort: 6060
  secret:
    # change this value
    jwt: ecb22bc24e7d4061f7ed690ccd5846d7d73f5d2b9733267e12f56790398d908a
  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  storage:
    className: local-path
    request: 1Ti
  replicaCount: 1

hoodi:
  image:
    repository: us-docker.pkg.dev/evmchain/images/taiko-geth
    tag: v1.5.0
    pullPolicy: Always
  id: 167009
  bootnodes: "enode://eb5079aae185d5d8afa01bfd2d349da5b476609aced2b57c90142556cf0ee4a152bcdd724627a7de97adfc2a68af5742a8f58781366e6a857d4bde98de6fe986@34.44.53.195:30303,enode://b054002f068f30568aad39271462c053463edb4a3d3c19b71b475fa044805d7e2fda39c482eba183f9d1f76fb579a8e47c0c054bb819c2bbcb331c0aac7464c2@34.27.167.246:30303"

mainnet:
  image:
    repository: us-docker.pkg.dev/evmchain/images/taiko-geth
    tag: v1.5.0
    pullPolicy: Always
  id: 167000
  bootnodes: "enode://c263741b17759f3850d24d67d6c3cbc307c73e17d80c6b12a63a4792a10529d1125d00ecf7ef4c9b0dc51d28b94dfc1b8798fb524f61a1f93946748649f73b23@34.142.239.251:4001?discport=30304,enode://2f37c3affd83274b262fa2a259d32d41510dd5a48d6e916696efe7f1598cb3f905305f5989e7b6607aab50697fb2e52cb4b6904116ed67cc5fcea1e6d66ccaba@35.247.159.156:4001?discport=30304,enode://dd83dedeff622ecfca0c5edf320266506c811539a553ddd91589cdfcc9bbd74d0d620f251d8d5e1180f19a446abbdd8b6b5301e9aa6cbad35cfd9716f80f2416@34.126.90.255:4001?discport=30304"
